name: Continuous Integration with GitHub Actions

on:
  push:
    branches: 
      - develop
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application
      working-directory: .
      run: mvn clean package

    - name: Build Docker Compose Application
      working-directory: .
      run: docker compose build
      
    - name: Push Docker Compose Application
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/sgc_consumer:latest ${{ secrets.DOCKER_USERNAME }}/sgc_consumer:${{ github.run_id }} 
        
        docker push ${{ secrets.DOCKER_USERNAME }}/sgc_consumer:${{ github.run_id }} 
        docker push ${{ secrets.DOCKER_USERNAME }}/sgc_consumer:latest
        
